/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.atom.ui.common.meta;

/**
 * A simple layout template system. String base and model base. A short version
 * of MetaWidget. http://metawidget.org
 * 
 * <p>How it works:<ul>
 * <li>It extract the template from string or from bean with annotations about layouting
 * 
 * <li>It build elements in that order, row by row...
 * 
 * <li>It binds value by reactive bean binding 
 * 
 * <li>String-still will be generated by Antrl StringTemplate
 * @author CuongNguyen
 */
public class GUILayoutTemplate {
    
    class Slot{
        
    }
    
    class Row{
        
    }
    
    class AlignMark{
        
    }
}
