/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package sg.atom.managex.api.memeto;

/**
 * FunctionMemeto save info generated by a {@link FunctionMemetoEdit}
 * 
 * @author cuong.nguyenmanh2
 */
public abstract class FunctionMemeto<T> implements IMemeto<T> {

    public abstract IMemeto<T> from(FunctionMemetoEdit<T> edit,IMemeto<T> wrapedMemeto);
}
